/**
 * sync-shared.mjs — single-source-of-truth sync from miniprogram CJS utils
 * to preview-app ESM modules.
 *
 * Source of truth: miniprogram/utils/<name>.js (room-scene-layout.js itself is
 * generated by tools/gen-room-master.js — never hand-edit either side).
 *
 * The transformation is deterministic: exact-string anchors are replaced; if an
 * anchor is missing (upstream drifted), the script throws so the port gets a
 * manual review instead of a silent mismatch.
 *
 *   node scripts/sync-shared.mjs          # regenerate the web copies
 *   node scripts/sync-shared.mjs --check  # verify committed files match; exit 1 on drift
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const SRC = join(root, '..', 'miniprogram', 'utils');

const banner = (name, extra) => `/**
 * GENERATED from miniprogram/utils/${name} by scripts/sync-shared.mjs — do not hand-edit.
 * Run \`npm run sync:shared\` to regenerate; \`npm test\` fails on drift.
${extra ? ` * ${extra}\n` : ''} */
`;

function mustReplace(src, anchor, replacement, label) {
  if (!src.includes(anchor)) {
    throw new Error(`[sync-shared] anchor not found (${label}): ${JSON.stringify(anchor.slice(0, 60))}… — upstream changed, review the port manually`);
  }
  return src.replace(anchor, replacement);
}

function mustRemove(src, anchor, label) {
  return mustReplace(src, anchor, '', label);
}

// ---- per-file deterministic transforms ----

function convertLayout(src) {
  let out = mustReplace(src, 'module.exports =', 'export default', 'layout export');
  return banner('room-scene-layout.js', 'Data itself generated by tools/gen-room-master.js.') + out;
}

function convertRoomHit(src) {
  let out = src;
  out = mustReplace(out, 'function contains(area, left, top) {', 'export function contains(area, left, top) {', 'hit contains');
  out = mustReplace(out, 'function hitTest(left, top, items) {', 'export function hitTest(left, top, items) {', 'hit hitTest');
  out = mustRemove(out, '\nmodule.exports = { contains, hitTest };\n', 'hit module.exports');
  return banner('room-hit.js') + out;
}

function convertRoomMap(src) {
  let out = src;
  // Web 版只保留 createMap(geometry, layout) 工厂路径：去掉 legacy room-layout 依赖
  out = mustRemove(out, `const Layout = require('./room-layout');\n\n`, 'map require');
  // 兜底几何换成 Master 几何（web 侧总是显式传入 SceneLayout.GEOMETRY）
  out = mustReplace(out, `const DEFAULT_GEOMETRY = {
  X0: 414,
  Y0: 414,
  SX: 274,
  SY: 144,
  depthTopMin: 50,
  depthTopMax: 85.75
};`, `const DEFAULT_GEOMETRY = {
  X0: 414,
  Y0: 235,
  SX: 480,
  SY: 250,
  depthTopMin: 32,
  depthTopMax: 85
};`, 'map DEFAULT_GEOMETRY');
  out = mustReplace(out, 'function createMap(geometry, layout) {',
    `export function createMap(geometry, layout) {
  if (!layout) throw new Error('[room-map] createMap requires an explicit layout (shared/room-scene-layout.js)');`, 'map createMap');
  out = mustReplace(out, 'const OBSTACLES = buildObstacles(layout || Layout);',
    'const OBSTACLES = buildObstacles(layout);', 'map obstacles');
  out = mustRemove(out, `
// 默认实例：旧几何（828 底图），对外 API 与 Phase 0 之前完全一致
module.exports = { createMap, ...createMap(DEFAULT_GEOMETRY) };
`, 'map default instance');
  return banner('room-map.js', 'Legacy room-layout require + default instance removed: factory-only path.') + out;
}

function convertPlayer(src) {
  let out = src;
  ['snapshot', 'toggle', 'play', 'switchTo', 'next', 'prev', 'seek', 'subscribe', 'applyRemote'].forEach((name) => {
    out = mustReplace(out, `function ${name}(`, `export function ${name}(`, `player ${name}`);
  });
  out = mustReplace(out, `module.exports = {
  subscribe,
  toggle,
  play,
  next,
  prev,
  seek,
  switchTo,
  applyRemote,
  snapshot
};`, `export default { subscribe, toggle, play, next, prev, seek, switchTo, applyRemote, snapshot };
`, 'player module.exports');
  return banner('player.js') + out;
}

function convertRecords(src) {
  let out = src;
  ['RECORD_COLORS', 'RECORD_TITLES', 'RECORDS', 'DEFAULT_SELECTION'].forEach((name) => {
    out = mustReplace(out, `const ${name} =`, `export const ${name} =`, `records ${name}`);
  });
  out = mustReplace(out, 'function readSelection(', 'export function readSelection(', 'records readSelection');
  out = mustReplace(out, 'function byId(', 'export function byId(', 'records byId');
  out = mustReplace(out, 'module.exports = { RECORDS, RECORD_COLORS, DEFAULT_SELECTION, readSelection, byId, MAX_PICK: 12 };',
    `export const MAX_PICK = 12;

export default { RECORDS, RECORD_COLORS, DEFAULT_SELECTION, readSelection, byId, MAX_PICK };`, 'records module.exports');
  return banner('records.js') + out;
}

const FILES = [
  { src: 'room-scene-layout.js', dest: 'src/shared/room-scene-layout.js', convert: convertLayout },
  { src: 'room-map.js', dest: 'src/shared/room-map.js', convert: convertRoomMap },
  { src: 'room-hit.js', dest: 'src/shared/room-hit.js', convert: convertRoomHit },
  { src: 'player.js', dest: 'src/state/player.js', convert: convertPlayer },
  { src: 'records.js', dest: 'src/state/records.js', convert: convertRecords }
];

const checkOnly = process.argv.includes('--check');
let drift = 0;

for (const f of FILES) {
  const source = readFileSync(join(SRC, f.src), 'utf8');
  const generated = f.convert(source);
  const destPath = join(root, f.dest);
  if (checkOnly) {
    let current = '';
    try { current = readFileSync(destPath, 'utf8'); } catch { /* missing = drift */ }
    if (current === generated) {
      console.log(`  ✓ ${f.dest} in sync`);
    } else {
      drift += 1;
      console.error(`  ✗ ${f.dest} DRIFTED from miniprogram/utils/${f.src} — run npm run sync:shared`);
    }
  } else {
    writeFileSync(destPath, generated);
    console.log(`[sync-shared] miniprogram/utils/${f.src} -> ${f.dest}`);
  }
}

if (checkOnly && drift) {
  console.error(`\n[sync-shared] ${drift} file(s) out of sync`);
  process.exit(1);
}
